[asset]
"zahnrad_logo.png" =            ["FILE", "~/routing/files/Zahnrad/assets/zahnrad_logo.png"]
"zahnrad_logo_small.png" =      ["FILE", "~/routing/files/Zahnrad/assets/zahnrad_logo_small.png"]
"zahnrad_title.png" =           ["FILE", "~/routing/files/Zahnrad/assets/zahnrad_title.png"]
"zahnrad_title+logo.png" =      ["FILE", "~/routing/files/Zahnrad/assets/zahnrad_title+logo.png"]

[download]
"zahnrad/v/1.0.0" =             ["DOWNLOAD", "~/routing/files/Zahnrad/versions/Zahnrad-1.0.0.mrpack"]
"zahnrad/v/1.1.0" =             ["DOWNLOAD", "~/routing/files/Zahnrad/versions/Zahnrad-1.1.0.mrpack"]
"zahnrad/v/1.1.1" =             ["DOWNLOAD", "~/routing/files/Zahnrad/versions/Zahnrad-1.1.1.mrpack"]
"zahnrad/v/1.2.0" =             ["DOWNLOAD", "~/routing/files/Zahnrad/versions/Zahnrad-1.2.0.mrpack"]
"zahnrad/v/1.3.0" =             ["DOWNLOAD", "~/routing/files/Zahnrad/versions/Zahnrad-1.3.0.mrpack"]

[resource]
"AllRightsReserved" =           ["FILE", "~/routing/files/AllRightsReserved.txt"]
"AllRightsReserved.txt" =       ["FILE", "~/routing/files/AllRightsReserved.txt"]
"allrightsreserved" =           ["FILE", "~/routing/files/AllRightsReserved.txt"]
"allrightsreserved.txt" =       ["FILE", "~/routing/files/AllRightsReserved.txt"]

[meta]
"zahnrad/v/latest" = 		["FILE", "~/routing/files/Zahnrad/meta/latest-version.txt"]